config/routes.rb
Rails.application.routes.draw do
  root 'sites#new'
  resources :sites, only: [:new, :create, :show]
  get '/:id', to: 'short_url#show', as: 'short_url'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_url_controller.rb
class ShortUrlController < ApplicationController
  def show
    @site = Site.find(params[:id])
    redirect_to @site.url
  end


end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to @site
    else
      render :new
    end
  end

    def show
      @site= Site.find{params[:id]}
    end


  private

  def site_params
    params.require(:site).permit(:url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sites/new.html.erb
<h1>Insert your URL</h1>
<%= form_with(model: @site, local: true) do |form| %>
  <div class = "field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class ="actions">
  <%= form.submit "Submit" %>

  </div>

<% end %>

app/views/sites/show.html.erb
<h1> Your shortened URL </h1>

<p>
<%= link_to short_url_path(@site), short_url_path(@site)%>
</p>